# Generated by Django 5.0.2 on 2024-02-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('product_name', models.CharField(max_length=250, verbose_name='Nombre de producto')),
                ('amount_product', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('monetary_amount_product', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto monetario')),
                ('record_type', models.PositiveIntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], default=1, verbose_name='Tipo de registro')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
