# Generated by Django 5.0.2 on 2024-02-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_creator_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='creator_record',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='monetary_amount_product',
            new_name='monetary_amount',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='amount_product',
            new_name='product_amount',
        ),
    ]
